server:
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: password
    key-store-type: PKCS12
    key-alias: tomcat
    key-password: password
    enabled: true
  port: 8443
spring:
  cloud:
    gateway:
      routes:
        - id: policy
          uri: http://policy:8081/
          predicates:
            - Path=/policy/**