server:
  ssl:
    key-store: classpath:certificate/keystore.p12
    key-store-password: password
    key-store-type: PKCS12
    key-alias: tomcat
    key-password: password
    enabled: true
    trust-store: classpath:certificate/keystore.p12
    trust-store-password: password
  port: 8443
  http2:
    enabled: false
spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
      routes:
        - id: policy
          uri: http://policy:8081/
          predicates:
            - Path=/policy/**
        - id: rate
          uri: http://rate:8083/
          predicates:
            - Path=/rate/**